version: '3.1'

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - ./testdata/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
